name: Python CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip

    - name: Run tests
      run: |
        python -m unittest discover tests

    - name: Increment version
      run: |
        version=$(cat version.txt)
        new_version=$(echo $version | awk -F. -v OFS=. '{$NF++; print}')
        echo $new_version > version.txt
        git config --global user.name "github-actions"
        git config --global user.email "github-actions@github.com"
        git add version.txt
        git commit -m "Atualiza para versão $new_version"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
